/**
 * early-donors.test.js — the committed borrowed plans still describe this catalog.
 *
 * `public/northeastern/early-donors.json` is derived data, regenerated by hand
 * (`node scripts/derive-early-donors.js --write`) while the programs and the
 * catalog under it refresh on a schedule. So the failure this file exists to catch
 * is staleness, which is exactly what a re-scrape produces if nobody reruns the
 * derivation: a course that no longer exists, a requirement a program dropped, or
 * a department that has since published a plan of its own and should no longer be
 * borrowing anyone else's.
 *
 * The load-bearing assertion is the third one. "A donor supplies timing for
 * courses the program already requires" is the whole safety argument for learning
 * from another program, and it is checked here against the live requirements
 * rather than trusted from the script that wrote the file.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { requiredBySubject } from "../../scripts/lib/early-donors.js";
import { loadCatalog } from "../../src/adapters/northeastern/courseCatalog.node.js";
import { programIdentity } from "../../src/core/programIdentity.js";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "../..");
const FILE = join(ROOT, "public/northeastern/early-donors.json");

const doc = existsSync(FILE) ? JSON.parse(readFileSync(FILE, "utf8")) : null;

/** Every program in the shipped corpus, by `programIdentity`. */
function corpus() {
  const out = new Map();
  for (const lvl of ["undergraduate", "graduate"]) {
    const base = join(ROOT, "data/northeastern/programs", lvl, "2026");
    if (!existsSync(base)) continue;
    for (const col of readdirSync(base)) {
      const cd = join(base, col);
      if (!statSync(cd).isDirectory()) continue;
      for (const key of readdirSync(cd)) {
        const rf = join(cd, key, "requirements.json");
        if (!existsSync(rf)) continue;
        const data = JSON.parse(readFileSync(rf, "utf8"));
        const id = programIdentity(data);
        if (id) out.set(id, { data, hasPlan: existsSync(join(cd, key, "plan.json")) });
      }
    }
  }
  return out;
}

const PROGRAMS = corpus();
const { courseMap } = loadCatalog();

/** Every course a borrowed plan places, with the program it was placed for. */
function placements() {
  const out = [];
  for (const [url, entry] of Object.entries(doc?.programs ?? {})) {
    for (const year of (entry.plan?.years ?? [])) {
      for (const term of (year.terms ?? [])) {
        for (const e of (term.entries ?? [])) {
          for (const key of (e.options?.[0] ?? [])) out.push({ url, key, term, entry });
        }
      }
    }
  }
  return out;
}

test("early donors › the file is present and not empty", () => {
  assert.ok(doc, `${FILE} is missing — run: node scripts/derive-early-donors.js --write`);
  const n = Object.keys(doc.programs ?? {}).length;
  // Not a target. This only catches a file that collapsed, the same rail
  // `derive-plan-order` applies to itself.
  assert.ok(n > 10, `only ${n} programs have a borrowed plan; the derivation lost its donors`);
  assert.ok(placements().length > 20, "no courses are placed at all");
});

test("early donors › the corpus is loaded, so the checks below are not vacuous", () => {
  assert.ok(PROGRAMS.size > 500, `only ${PROGRAMS.size} programs found`);
  assert.ok(Object.keys(courseMap).length > 5000, "the catalog did not load");
});

test("early donors › every borrowed course is one the program REQUIRES", () => {
  // The safety property. A donor may only say WHEN; a course the target does not
  // require would be this file adding coursework to someone's degree.
  const bad = [];
  for (const { url, key } of placements()) {
    const program = PROGRAMS.get(url);
    if (!program) continue;                       // reported by its own test below
    const required = new Set([...requiredBySubject(program.data).values()]
      .flatMap(set => [...set]));
    if (!required.has(key)) bad.push(`${program.data.name}: ${key}`);
  }
  assert.deepEqual(bad, [],
    "borrowed courses the program does not require — regenerate early-donors.json");
});

test("early donors › every borrowed course still exists in the catalog", () => {
  const gone = [...new Set(placements()
    .filter(p => !courseMap[p.key])
    .map(p => `${doc.programs[p.url].program}: ${p.key}`))];
  assert.deepEqual(gone, [], "courses the catalog no longer lists");
});

test("early donors › every program named still exists, by URL", () => {
  const missing = Object.keys(doc?.programs ?? {}).filter(u => !PROGRAMS.has(u));
  assert.deepEqual(missing, [], "programs that have moved or been retired");
});

test("early donors › no program that publishes its OWN plan is borrowing", () => {
  // Staleness in the direction that matters: a department has since published a
  // plan, so the engine would use theirs and this entry is dead weight at best.
  const own = Object.keys(doc?.programs ?? {})
    .filter(u => PROGRAMS.get(u)?.hasPlan)
    .map(u => doc.programs[u].program);
  assert.deepEqual(own, [], "these publish a plan now — regenerate early-donors.json");
});

test("early donors › a donor is never the program itself", () => {
  const self = [];
  for (const [url, entry] of Object.entries(doc?.programs ?? {})) {
    const name = PROGRAMS.get(url)?.data?.name;
    for (const d of (entry.donors ?? [])) if (d.from === name) self.push(name);
  }
  assert.deepEqual(self, []);
});

test("early donors › every term is a slot the planner has", () => {
  // The engine maps a borrowed term onto the shape by season, so a season it does
  // not generate would silently drop the whole term.
  const KNOWN = new Set(["fall", "spring", "sumA", "sumB"]);
  const bad = [...new Set(Object.values(doc?.programs ?? {})
    .flatMap(e => (e.plan?.years ?? []).flatMap(y => (y.terms ?? []).map(t => t.type)))
    .filter(t => !KNOWN.has(t)))];
  assert.deepEqual(bad, []);
});

test("early donors › no course is placed twice in one plan", () => {
  // One registration, one term. A cross-listed course reachable from two clusters
  // is the way this happens.
  const bad = [];
  for (const [url, entry] of Object.entries(doc?.programs ?? {})) {
    const seen = new Set();
    for (const year of (entry.plan?.years ?? [])) {
      for (const term of (year.terms ?? [])) {
        for (const e of (term.entries ?? [])) {
          const key = e.options?.[0]?.[0];
          if (seen.has(key)) bad.push(`${entry.program}: ${key}`);
          seen.add(key);
        }
      }
    }
  }
  assert.deepEqual(bad, []);
});

test("early donors › every recorded similarity clears the file's own floor", () => {
  const floor = doc?.filters?.minSimilarity ?? 0;
  const weak = Object.values(doc?.programs ?? {})
    .flatMap(e => (e.donors ?? []).filter(d => d.similarity < floor)
      .map(d => `${e.program}/${d.subject} ${d.similarity}`));
  assert.deepEqual(weak, [], `donors below the stated floor of ${floor}`);
});
