// INVARIANT · every committed src/data/**/plan.json, as it will be shipped.
//
// The contract tests read six fixtures. That is enough to pin the parser's
// behaviour and not enough to see the corpus: "Summer Full Semester" appears in
// 18 programs, none of them a fixture, and it produced `type: null` — a term
// the planner has no slot for — while the fixture-scoped "every term is
// understood" test passed. These tests read the real files instead, so the next
// header the catalog invents fails here rather than in a student's plan.
//
// Committed data only — no network, no deps.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readdirSync, statSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "../helpers/paths.js";

/** Every plan.json under the live program trees, as [relPath, grid]. */
function loadPlans() {
  const out = [];
  const walk = (dir) => {
    let entries;
    try { entries = readdirSync(dir); } catch { return; }
    for (const e of entries) {
      const p = join(dir, e);
      if (statSync(p).isDirectory()) walk(p);
      else if (e === "plan.json") out.push([p.slice(ROOT.length + 1), JSON.parse(readFileSync(p, "utf8"))]);
    }
  };
  walk(join(ROOT, "src/data/majors"));
  walk(join(ROOT, "src/data/grad-majors"));
  return out;
}

const PLANS = loadPlans();

/**
 * The only semester ids the planner has slots for. Generated by
 * src/core/semGrid.js from the calendar adapter; a plan naming anything else
 * describes a term that cannot be shown.
 */
const SEMESTER_IDS = new Set(["fall", "spring", "sumA", "sumB"]);

test("sample plans › the corpus exists at all", () => {
  // A zero here means the scrapers stopped emitting plans and every test below
  // would vacuously pass.
  assert.ok(PLANS.length > 300, `only ${PLANS.length} plan files committed`);
});

test("sample plans › every term maps to a real planner semester", () => {
  const bad = [];
  for (const [path, grid] of PLANS) {
    for (const plan of grid.plans) {
      for (const year of plan.years) {
        for (const term of year.terms) {
          if (!SEMESTER_IDS.has(term.type)) bad.push(`${path}: "${term.term}" → ${term.type}`);
        }
      }
    }
  }
  assert.deepEqual(bad.slice(0, 10), [],
    `${bad.length} terms have no planner slot — add them to TERM_TYPES in scripts/lib/plan-grid.js`);
});

test("sample plans › a full summer anchors to the first half and says so", () => {
  // It spans both halves, which the planner cannot represent in one slot, so
  // it takes sumA (where the course starts) and carries fullSummer rather than
  // silently passing as a first-half term.
  let seen = 0;
  for (const [path, grid] of PLANS) {
    for (const plan of grid.plans) {
      for (const year of plan.years) {
        for (const term of year.terms) {
          if (!term.fullSummer) continue;
          seen++;
          assert.equal(term.type, "sumA", `${path}: full summer anchored to ${term.type}`);
        }
      }
    }
  }
  assert.ok(seen > 0, "no full-summer terms found — the mapping may have been dropped");
});

test("sample plans › plan labels are unique within a program", () => {
  // The label is how a saved choice points at a plan. Two the same and the
  // student's selection cannot be resolved back.
  for (const [path, grid] of PLANS) {
    const labels = grid.plans.map(p => p.label);
    assert.equal(new Set(labels).size, labels.length, `${path}: ${JSON.stringify(labels)}`);
    for (const l of labels) assert.ok(l && l.trim(), `${path}: blank plan label`);
  }
});

test("sample plans › no plan is empty", () => {
  // An empty plan is a parse failure that reached disk: it would appear in the
  // UI as a sample plan that does nothing when applied.
  for (const [path, grid] of PLANS) {
    assert.ok(grid.plans.length, `${path}: no plans`);
    for (const plan of grid.plans) {
      const entries = plan.years.flatMap(y => y.terms.flatMap(t => t.entries));
      assert.ok(entries.length, `${path} / ${plan.label}: no entries`);
    }
  }
});

test("sample plans › every entry is a kind the applier knows", () => {
  const KINDS = new Set(["course", "courses", "choice", "coop", "placeholder", "vacation"]);
  for (const [path, grid] of PLANS) {
    for (const plan of grid.plans) {
      for (const year of plan.years) {
        for (const term of year.terms) {
          for (const e of term.entries) {
            assert.ok(KINDS.has(e.kind), `${path}: unknown entry kind ${e.kind}`);
            // Only the two courseless kinds may omit codes, and the three
            // course kinds must never be empty — an entry with a course kind
            // and no codes would place nothing while claiming to place
            // something.
            if (e.kind === "coop") {
              // A co-op MAY name the course a student registers for
              // (COOP 3945 and friends); it is still a work term, not a card.
              for (const c of e.codes ?? []) {
                assert.match(c, /^COOP\d/, `${path}: coop entry carries a non-coop code ${c}`);
              }
            } else if (e.kind === "placeholder" || e.kind === "vacation") {
              // Neither names a course: one is a slot to fill, the other a
              // term off. Both would be a lie with a code attached.
              assert.equal(e.codes, undefined, `${path}: ${e.kind} carries codes`);
            } else {
              assert.ok(e.codes?.length, `${path}: ${e.kind} with no codes`);
            }
          }
        }
      }
    }
  }
});

test("sample plans › course codes are well formed", () => {
  // They are looked up against the catalog by exact key, so a malformed one
  // silently becomes an unplaceable entry rather than an error.
  const KEY = /^[A-Z]{2,6}\d{3,4}[A-Z]?$/;
  for (const [path, grid] of PLANS) {
    for (const plan of grid.plans) {
      for (const year of plan.years) {
        for (const term of year.terms) {
          for (const e of term.entries) {
            for (const code of e.codes ?? []) {
              assert.match(code, KEY, `${path}: ${code}`);
            }
          }
        }
      }
    }
  }
});

test("sample plans › a vacation is a term off, not a slot to fill", () => {
  // 782 cells say "Vacation". Reading one as a placeholder would put an empty
  // requirement slot in a semester the department is telling you to take off,
  // and would carry credit hours toward a term load meant to be zero.
  let seen = 0;
  for (const [path, grid] of PLANS) {
    for (const plan of grid.plans) {
      for (const year of plan.years) {
        for (const term of year.terms) {
          for (const e of term.entries) {
            if (e.kind !== "vacation") continue;
            seen++;
            assert.equal(e.codes, undefined, `${path}: vacation carries codes`);
            assert.equal(e.sh, undefined, `${path}: vacation carries credit hours`);
          }
        }
      }
    }
  }
  assert.ok(seen > 100, `only ${seen} vacation entries — the classification may have been dropped`);
});

test("sample plans › entries carry the credit hours the grid states", () => {
  // An unfilled slot has to contribute to its term's load, or a freshly loaded
  // template reads at roughly half the credits the department states and every
  // semester looks like a warning that is not real. The grid gives each cell
  // its own hours; this is the check that we are still reading them.
  let withSh = 0, total = 0;
  for (const [path, grid] of PLANS) {
    for (const plan of grid.plans) {
      for (const year of plan.years) {
        for (const term of year.terms) {
          for (const e of term.entries) {
            if (e.kind === "vacation") continue;
            total++;
            if (e.sh == null) continue;
            withSh++;
            assert.ok(Number.isFinite(e.sh) && e.sh >= 0, `${path}: sh ${e.sh} on "${e.text}"`);
            assert.ok(e.sh <= 24, `${path}: implausible sh ${e.sh} on "${e.text}"`);
          }
        }
      }
    }
  }
  // Cells with no hours column are prose notes rather than slots, so the bar
  // is high coverage, not total.
  assert.ok(withSh / total > 0.95, `only ${(100 * withSh / total).toFixed(1)}% of entries carry credit hours`);
});
