// ═══════════════════════════════════════════════════════════════════
// PLAN LABELS — the strings that say a plan was generated
//
// A LEAF module, and that is the whole reason it exists as one. Two consumers need these and
// they already import each other: `planTemplate.js` renders the label and imports
// `applySamplePlan.js`, which needs to recognise it when building a reservation's provenance.
// Putting the constants in either would make a cycle out of three strings, so they live where
// nothing else does. `planTemplate.js` re-exports them, so no existing importer changes.
// ═══════════════════════════════════════════════════════════════════

/**
 * The label a CHART-generated variant carries when the engine names it itself.
 *
 * It lives here, in core, and not in the engine that writes it, because both
 * sides need it: `emitPlan` stamps it onto the artifact, and the UI has to
 * recognise it afterwards. `appliedTemplate` persists nothing about provenance
 * except this string, so the string IS the test for "was this generated" — and a
 * test spelled out twice is one rename away from being a test for nothing.
 */
export const GENERATED_PLAN_LABEL = "Generated by NU Map";

/**
 * What this label used to say, kept because it is PERSISTED.
 *
 * "CHART" is the engine's internal name and means nothing to a student — the same
 * judgement `PlanSourceToggle` already made when its second label stopped saying it.
 * But this string is not only rendered: `appliedTemplate` stores it, share links carry
 * it, and it is the ONLY record that a plan was generated rather than loaded. So a plain
 * rename would quietly reclassify every plan a student saved before today as a
 * department's published variant — the byline would reappear in the collapsed row and
 * `isGeneratedPlanLabel` would answer false about a plan this engine wrote.
 *
 * Recognised, never written. Nothing produces it any more; it only has to be readable.
 */
export const LEGACY_GENERATED_PLAN_LABEL = "Generated by CHART";

/**
 * The PROVENANCE namespace for a generated plan — never displayed, never changed.
 *
 * ── Why this exists, measured ───────────────────────────────────────
 *
 * `originKey(planLabel, …)` builds a reservation's origin out of the plan's LABEL, and
 * `seenOrigins` is the only thing stopping a re-apply creating every card a second time. So the
 * label is not merely a caption: it is half of a persisted key. Renaming it from "Generated by
 * CHART" to "Generated by NU Map" therefore did this, silently and with no note:
 *
 *     applied once   (old label)   3 reservations
 *     regenerated    (new label)   6 reservations
 *     re-applied     (old label)   3 reservations   <- the de-dupe, working
 *
 * A student who saved a generated plan before the rename and regenerates after it gets a
 * complete duplicate set. That is defect A2#18, caused by a change that looked cosmetic — and
 * the corpus fingerprint gate cannot see it, because it hashes the emitted document and this is
 * about state already on the student's machine.
 *
 * ── Why the value is the OLD string, and must stay so ───────────────
 *
 * Any new token would have exactly the same effect once, on the transition. Keeping the
 * historical value means every origin ever written still matches, so no migration is needed and
 * no plan doubles. It is never rendered — `GENERATED_PLAN_LABEL` is what a reader sees — so it
 * carries no product meaning and there is nothing to keep in step with the UI.
 *
 * **Do not "tidy" this to match the display label.** That is the bug, spelled the other way.
 */
export const GENERATED_ORIGIN_NS = LEGACY_GENERATED_PLAN_LABEL;

/**
 * Is a variant label one the engine gave itself?
 *
 * Only the engine's own defaults count, current and legacy. A department is free to
 * publish a variant called "Generated by NU Map" — nothing stops it — and if one ever
 * does, treating it as generated costs a hidden label in a collapsed row, which is the
 * cheap direction to be wrong in.
 */
export const isGeneratedPlanLabel = (label) =>
  (label ?? "") === GENERATED_PLAN_LABEL || (label ?? "") === LEGACY_GENERATED_PLAN_LABEL;
