// ═══════════════════════════════════════════════════════════════════
// ADAPTER: northeastern/courseCatalog  (implements ICourseCatalog)
//
// DATA SOURCE HISTORY
// ───────────────────
// Course data originally came from the external/nu-courses git submodule
// (a fork of ninest/nu-courses), which re-served data from SearchNEU via
// husker.vercel.app. This let us bootstrap quickly with a ready-made API.
// The downside: dependency on an external hosted service we didn't control,
// with no ability to backfill history or shape the schema.
//
// We later built our own scrapers (scripts/scrape-catalog.js,
// scripts/scrape-availability.js) that pull directly from
// catalog.northeastern.edu and nubanner.neu.edu, writing to:
//   public/northeastern/catalog-courses.json  — course metadata
//   public/northeastern/term-history.json     — Banner enrollment history
//
// These files are now the source of truth. The external submodule is no
// longer in the fetch path.
//
// Primary catalog:  public/northeastern/catalog-courses.json (course metadata)
// Term history:     public/northeastern/term-history.json (Banner availability)
//   — generated by scripts/scrape-availability.js
//   — keyed by courseId → { termCode: boolean }
//
// Raw term codes: NEU Banner — YYYY = AY end year; 10=Fall, 30=Spring,
//                 40=Summer 1, 60=Summer 2  (decoded during normalization)
// ═══════════════════════════════════════════════════════════════════
import { subjectColor } from "../../core/courseModel.js";
import calendar from "./calendar.js";

const LOCAL_URL    = `${import.meta.env.BASE_URL}northeastern/catalog-courses.json`;
const HISTORY_URL  = `${import.meta.env.BASE_URL}northeastern/term-history.json`;
const OFFERING_URL = `${import.meta.env.BASE_URL}northeastern/offering-summary.json`;
const COLLEGES_URL = `${import.meta.env.BASE_URL}northeastern/subject-colleges.json`;
// Supplemental nuPath source — catalog scraper sometimes drops nuPath on full re-scrapes.
// all-courses.json (SearchNEU) is used only to back-fill nuPath when catalog-courses has none.
const ALL_COURSES_URL = `${import.meta.env.BASE_URL}northeastern/all-courses.json`;

// ── Helpers ──────────────────────────────────────────────────────

/**
 * Earliest term code (numeric) where the course was ever confirmed offered.
 * Returns null when no true entries exist.
 * @param {Record<string,boolean>} termHistory
 * @returns {number|null}
 */
function computeBirthTermCode(termHistory) {
  let birth = null;
  for (const [code, offered] of Object.entries(termHistory)) {
    if (offered === true) {
      const n = Number(code);
      if (birth === null || n < birth) birth = n;
    }
  }
  return birth;
}

/**
 * Compute which semester type IDs a course is offered in from termHistory.
 * Only entries on or after birthTermCode are considered — earlier entries are
 * pre-existence noise (Banner returning false before the course was created).
 * When post-birth history has only true entries, all decoded semTypes are included.
 * When it has mixed entries, a semType is included only if offered in ≥ 50%.
 * @param {Record<string,boolean>} termHistory
 * @param {number|null} birthTermCode
 */
function deriveTerms(termHistory, birthTermCode = null) {
  const entries = Object.entries(termHistory)
    .filter(([code]) => birthTermCode === null || Number(code) >= birthTermCode);
  if (entries.length === 0) return [];

  const hasNegative = entries.some(([, v]) => v === false);
  if (!hasNegative) {
    return [...new Set(entries.map(([code]) => calendar.decodeTermCode(code)).filter(Boolean))];
  }

  const semTypeIds = [...new Set(entries.map(([code]) => calendar.decodeTermCode(code)).filter(Boolean))];
  return semTypeIds.filter(id => {
    const ofType = entries.filter(([code]) => calendar.decodeTermCode(code) === id);
    return ofType.filter(([, v]) => v).length / ofType.length >= 0.5;
  });
}

// ── Normalization ────────────────────────────────────────────────

/** Enrollment-restriction patterns sometimes stored in the description field instead of actual content. */
const RESTRICTION_ONLY = /^(not open to|open only to|restricted to|required only for|graduate students only|undergraduate students only|for [a-z, ]+(students|majors|minors))/i;

function sanitizeDesc(raw) {
  const s = (raw || "").trim();
  if (!s) return "";
  if (s.length <= 150 && RESTRICTION_ONLY.test(s)) return "";
  return s;
}

/**
 * Normalize a raw catalog record into the internal Course shape.
 * Returns null if the record is missing a subject or number.
 *
 * @param {object} raw
 * @returns {import('../../ports/ICourseCatalog.js').Course|null}
 */
function normalizeCourse(raw, subjectColleges = {}, nuPathSupp = {}) {
  const subject = (raw.subject || raw.subjectCode || "").toUpperCase().trim();
  const number  = (raw.number  || raw.courseNumber || raw.num || "").trim();
  if (!subject || !number) return null;

  const id    = `${subject}${number}`;
  const title = raw.title || raw.name || "";
  const sh    = typeof raw.credits     === "number" ? raw.credits
               : typeof raw.credit     === "number" ? raw.credit
               : typeof raw.creditHours=== "number" ? raw.creditHours
               : 4;

  // sections[]{term} — de-duplicate term codes
  const rawTermCodes = raw.terms?.length
    ? raw.terms
    : (raw.sections || []).map(s => (typeof s === "string" ? s : s?.term ?? "")).filter(Boolean);
  const uniqueCodes = [...new Set(rawTermCodes)];

  // Build termHistory: each code we have section data for is confirmed offered (true).
  // false entries are added later when term-history.json is merged in fetchAll().
  const termHistory = {};
  for (const code of uniqueCodes) {
    if (calendar.decodeTermCode(code)) termHistory[code] = true;
  }

  const birthTermCode = computeBirthTermCode(termHistory);
  const uniqueTerms   = deriveTerms(termHistory, birthTermCode);

  const shMax = typeof raw.creditsMax === "number" && raw.creditsMax !== sh
    ? raw.creditsMax : null;
  const shMin = shMax !== null ? (sh ?? 4) : null;

  return {
    id, subject, number,
    code:         `${subject} ${number}`,
    title:        title.trim(),
    desc:         sanitizeDesc(raw.description),
    sh:           sh ?? 4,
    shMin,
    shMax,
    scheduleType: raw.scheduleType || "",
    prereqs:      raw.prereqs ?? raw.prerequisites ?? [],
    coreqs:       raw.coreqs  ?? raw.corequisites  ?? [],
    termHistory,
    birthTermCode,
    terms:        uniqueTerms,
    attributes:   (raw.nuPath?.length ? raw.nuPath : nuPathSupp[id]) ?? raw.attributes ?? [],
    color:        subjectColor(subject),
    isCps:        (subjectColleges[subject] ?? "") === "PS",
  };
}

// ── Fetch ────────────────────────────────────────────────────────

async function tryFetch(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} from ${url}`);
  const text = await res.text();
  if (text.trim().startsWith("<")) throw new Error(`Got HTML (not JSON) from ${url}`);
  return JSON.parse(text);
}

// ── Adapter ──────────────────────────────────────────────────────

/** @type {import('../../ports/ICourseCatalog.js').ICourseCatalog} */
export default {
  /**
   * Fetch the full course catalog and return all courses normalized to the Course shape.
   * Tries the bundled local JSON first; falls back to the live API.
   * Then merges term-history.json (if present) to enrich termHistory and recompute terms.
   */
  async fetchAll() {
    // Start the small optional fetches immediately while catalog loads.
    const collegesPromise = tryFetch(COLLEGES_URL);
    const historyPromise  = tryFetch(HISTORY_URL);
    const offeringPromise = tryFetch(OFFERING_URL);

    // Catalog is required — fetch it first so we can gate the supplemental download.
    let catalogJson;
    try {
      catalogJson = await tryFetch(LOCAL_URL);
    } catch (err) {
      throw new Error(`Could not load course catalog from ${LOCAL_URL}: ${err.message}`);
    }
    const raw = Array.isArray(catalogJson) ? catalogJson : Object.values(catalogJson).flat();

    // Skip all-courses.json (5.8 MB) when the build-time nuPath merge has already run
    // (coverage ≥ 10%). Fall back to fetching it automatically if coverage looks wrong,
    // e.g. after a scrape that wiped nuPath or if merge-nupath.js was not run.
    const nuPathCoverage = raw.filter(c => c.nuPath?.length > 0).length / raw.length;
    const suppPromise = nuPathCoverage >= 0.10
      ? Promise.resolve(null)
      : tryFetch(ALL_COURSES_URL);

    const [allCoursesResult, collegesResult, historyResult, offeringResult] = await Promise.allSettled([
      suppPromise,
      collegesPromise,
      historyPromise,
      offeringPromise,
    ]);

    // Back-fill nuPath from all-courses.json if the supplemental fetch ran.
    const nuPathSupp = {};
    if (allCoursesResult.status === "fulfilled" && Array.isArray(allCoursesResult.value)) {
      for (const c of allCoursesResult.value) {
        const id = `${(c.subject || "").toUpperCase().trim()}${(c.number || "").trim()}`;
        if (id && c.nuPath?.length) nuPathSupp[id] = c.nuPath;
      }
    }

    const subjectColleges = collegesResult.status === "fulfilled" ? collegesResult.value : {};
    const courses = raw.map(r => normalizeCourse(r, subjectColleges, nuPathSupp)).filter(Boolean);

    // Merge Banner availability history + per-term offering detail if present.
    // Both are optional — app works without them.
    const history = historyResult.status === "fulfilled" && historyResult.value && typeof historyResult.value === "object"
      ? historyResult.value : null;
    const offering = offeringResult.status === "fulfilled" && offeringResult.value && typeof offeringResult.value === "object"
      ? offeringResult.value : null;

    if (!history && !offering) return courses;

    return courses.map(course => {
      let c = course;
      const hist = history?.[course.id];
      if (hist && typeof hist === "object") {
        // Only merge past terms — future terms with false values skew probability.
        const pastHist = Object.fromEntries(
          Object.entries(hist).filter(([code]) => calendar.isTermPast(code))
        );
        const termHistory   = { ...course.termHistory, ...pastHist };
        const birthTermCode = computeBirthTermCode(termHistory);
        c = { ...course, termHistory, birthTermCode, terms: deriveTerms(termHistory, birthTermCode) };
      }
      const off = offering?.[course.id];
      return off ? { ...c, offering: off } : c;
    });
  },

  /** Normalize a single raw catalog record into the Course shape. */
  normalize: normalizeCourse,

  /**
   * Return the URL for the official Northeastern course catalog page for a course.
   * Links to the subject section; the registrar does not offer per-course-number deep links.
   */
  courseUrl(course) {
    return `https://catalog.northeastern.edu/course-descriptions/${course.subject.toLowerCase()}/`;
  },

  getSources() {
    return [
      {
        id:      "catalog",
        label:   "catalog.northeastern.edu",
        url:     "https://catalog.northeastern.edu/course-descriptions/",
        usedFor: "course catalog data",
      },
      {
        id:      "nubanner",
        label:   "nubanner.neu.edu",
        url:     "https://nubanner.neu.edu/StudentRegistrationSsb",
        usedFor: "term availability history",
      },
    ];
  },
};
