// ═══════════════════════════════════════════════════════════════════
// ADAPTER: northeastern/courseCatalog  (implements ICourseCatalog)
//
// DATA SOURCE HISTORY
// ───────────────────
// Course data originally came from an external/nu-courses git submodule
// (a fork of ninest/nu-courses, since removed), which re-served data from SearchNEU via
// husker.vercel.app. This let us bootstrap quickly with a ready-made API.
// The downside: dependency on an external hosted service we didn't control,
// with no ability to backfill history or shape the schema.
//
// We later built our own scrapers (scripts/scrape-catalog.js,
// scripts/scrape-availability.js) that pull directly from
// catalog.northeastern.edu and nubanner.neu.edu, writing to:
//   public/northeastern/catalog-courses.json  — course metadata
//   public/northeastern/term-history.json     — Banner enrollment history
//
// These files are now the source of truth. The external submodule is no
// longer in the fetch path.
//
// Primary catalog:  public/northeastern/catalog-courses.json (course metadata)
// Term history:     public/northeastern/term-history.json (Banner availability)
//   — generated by scripts/scrape-availability.js
//   — keyed by courseId → { termCode: boolean }
//
// Raw term codes: NEU Banner — YYYY = AY end year; 10=Fall, 30=Spring,
//                 40=Summer 1, 60=Summer 2  (decoded during normalization)
// ═══════════════════════════════════════════════════════════════════
import { normalizeCourse, mergeHistoryAndOffering } from "./courseNorm.js";

// Verified RateMyHusky link directory, populated by fetchAll() and read by the
// URL builders below. Module-level so the singleton adapter can expose
// synchronous courseUrl-style helpers to the UI after the one load.
//   profs   — instructor name → professor-page slug
//   courses — Set of course codes that actually have a RateMyHusky page
let ratemyhuskyProfs = {};
let ratemyhuskyCourses = new Set();

// Subject code → full display name ("ABRC" → "Study Abroad - CPS Specialty"),
// populated by fetchAll() and read by subjectName() below. A pill and a bank
// section header only have room for the code, so this is what their hover
// cards reveal. Optional asset: absent file just means no card appears.
let subjectDisplayNames = {};

const LOCAL_URL    = `${import.meta.env.BASE_URL}northeastern/catalog-courses.json`;
const HISTORY_URL  = `${import.meta.env.BASE_URL}northeastern/term-history.json`;
const OFFERING_URL = `${import.meta.env.BASE_URL}northeastern/offering-summary.json`;
const COLLEGES_URL = `${import.meta.env.BASE_URL}northeastern/subject-colleges.json`;
const SUBJECTS_URL = `${import.meta.env.BASE_URL}northeastern/subjects.json`;
// Verified RateMyHusky professor slugs (instructor name → page slug), built
// monthly by scripts/scrape-ratemyhusky.js from RateMyHusky's sitemap. Only a
// link directory — no ratings content — used to point instructor links at a
// real page instead of a guessed slug that could 404. Optional: absent file
// just means professor links fall back to the RateMyHusky browse page.
const RATEMYHUSKY_URL = `${import.meta.env.BASE_URL}northeastern/ratemyhusky.json`;
const RATEMYHUSKY_BASE = "https://ratemyhusky.com";
// Supplemental nuPath source — catalog scraper sometimes drops nuPath on full re-scrapes.
// all-courses.json (SearchNEU) is used only to back-fill nuPath when catalog-courses has none.
const ALL_COURSES_URL = `${import.meta.env.BASE_URL}northeastern/all-courses.json`;

// ── Fetch ────────────────────────────────────────────────────────

async function tryFetch(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} from ${url}`);
  const text = await res.text();
  if (text.trim().startsWith("<")) throw new Error(`Got HTML (not JSON) from ${url}`);
  return JSON.parse(text);
}

// ── Adapter ──────────────────────────────────────────────────────

/** @type {import('../../ports/ICourseCatalog.js').ICourseCatalog} */
export default {
  /**
   * Fetch the full course catalog and return all courses normalized to the Course shape.
   * Loads the bundled local catalog JSON (required — no remote fallback).
   * Then merges term-history.json (if present) to enrich termHistory and recompute terms.
   */
  async fetchAll() {
    // Start the small optional fetches immediately while catalog loads.
    const collegesPromise = tryFetch(COLLEGES_URL);
    const historyPromise  = tryFetch(HISTORY_URL);
    const offeringPromise = tryFetch(OFFERING_URL);
    const rmhPromise      = tryFetch(RATEMYHUSKY_URL);
    const subjectsPromise = tryFetch(SUBJECTS_URL);

    // Catalog is required — fetch it first so we can gate the supplemental download.
    let catalogJson;
    try {
      catalogJson = await tryFetch(LOCAL_URL);
    } catch (err) {
      throw new Error(`Could not load course catalog from ${LOCAL_URL}: ${err.message}`);
    }
    const raw = Array.isArray(catalogJson) ? catalogJson : Object.values(catalogJson).flat();

    // Skip all-courses.json (5.8 MB) when the build-time nuPath merge has already run
    // (coverage ≥ 10%). Fall back to fetching it automatically if coverage looks wrong,
    // e.g. after a scrape that wiped nuPath or if merge-nupath.js was not run.
    const nuPathCoverage = raw.filter(c => c.nuPath?.length > 0).length / raw.length;
    const suppPromise = nuPathCoverage >= 0.10
      ? Promise.resolve(null)
      : tryFetch(ALL_COURSES_URL);

    const [allCoursesResult, collegesResult, historyResult, offeringResult, rmhResult, subjectsResult] = await Promise.allSettled([
      suppPromise,
      collegesPromise,
      historyPromise,
      offeringPromise,
      rmhPromise,
      subjectsPromise,
    ]);

    // Subject display names — optional, like the RateMyHusky map above: a failed
    // or absent fetch leaves it empty and the hover cards simply never appear.
    subjectDisplayNames = (subjectsResult.status === "fulfilled" && subjectsResult.value && typeof subjectsResult.value === "object")
      ? subjectsResult.value : {};

    // Cache the verified RateMyHusky slug map for the URL builders below.
    // Optional asset — a failed/absent fetch just leaves the map empty and
    // professor links fall back to the RateMyHusky browse page.
    ratemyhuskyProfs = (rmhResult.status === "fulfilled" && rmhResult.value && typeof rmhResult.value.profs === "object")
      ? rmhResult.value.profs : {};
    ratemyhuskyCourses = new Set(
      (rmhResult.status === "fulfilled" && Array.isArray(rmhResult.value?.courses)) ? rmhResult.value.courses : []
    );

    // Back-fill nuPath from all-courses.json if the supplemental fetch ran.
    const nuPathSupp = {};
    if (allCoursesResult.status === "fulfilled" && Array.isArray(allCoursesResult.value)) {
      for (const c of allCoursesResult.value) {
        const id = `${(c.subject || "").toUpperCase().trim()}${(c.number || "").trim()}`;
        if (id && c.nuPath?.length) nuPathSupp[id] = c.nuPath;
      }
    }

    const subjectColleges = collegesResult.status === "fulfilled" ? collegesResult.value : {};
    const courses = raw.map(r => normalizeCourse(r, subjectColleges, nuPathSupp)).filter(Boolean);

    // Merge Banner availability history + per-term offering detail if present.
    // Both are optional — app works without them.
    const history = historyResult.status === "fulfilled" && historyResult.value && typeof historyResult.value === "object"
      ? historyResult.value : null;
    const offering = offeringResult.status === "fulfilled" && offeringResult.value && typeof offeringResult.value === "object"
      ? offeringResult.value : null;

    return mergeHistoryAndOffering(courses, history, offering);
  },

  /** Normalize a single raw catalog record into the Course shape. */
  normalize: normalizeCourse,

  /**
   * Return the URL for the official Northeastern course catalog page for a course.
   * Links to the subject section; the registrar does not offer per-course-number deep links.
   */
  courseUrl(course) {
    return `https://catalog.northeastern.edu/course-descriptions/${course.subject.toLowerCase()}/`;
  },

  /**
   * RateMyHusky course page (TRACE + RateMyProfessor + Reddit reviews), or null
   * when RateMyHusky has no page for this course. RateMyHusky's SPA serves a
   * 200 shell for ANY code, so we can't tell coverage from the URL — instead we
   * check the verified course-code set (scraped from /api/courses-catalog) and
   * return null for the ~half of the catalog it doesn't cover, so the UI omits
   * the link rather than linking to an empty page. Third-party, student-run
   * aggregator; we only link out.
   */
  courseRatingsUrl(course) {
    const code = `${course.subject}${course.number}`;
    return ratemyhuskyCourses.has(code) ? `${RATEMYHUSKY_BASE}/courses/${code}` : null;
  },

  /**
   * RateMyHusky professor page for an instructor name, or null when we have no
   * verified page with reviews. ratemyhusky.json only maps names to pages that
   * actually have reviews, so a non-null result never lands on an empty or
   * missing profile; the UI renders the name as plain text when this is null.
   * Names come straight from course.offering.prof, matching the map's keys.
   */
  profRatingsUrl(name) {
    const slug = ratemyhuskyProfs[name];
    return slug ? `${RATEMYHUSKY_BASE}/professors/${slug}` : null;
  },

  /**
   * Full display name for a subject code, or null when the catalog publishes
   * none (and until fetchAll has run). Codes in the app are already uppercase,
   * but normalising here means a caller passing "cs" still resolves.
   */
  subjectName(subject) {
    if (!subject) return null;
    return subjectDisplayNames[String(subject).toUpperCase()] ?? null;
  },

  getSources() {
    return [
      {
        id:      "catalog",
        label:   "catalog.northeastern.edu",
        url:     "https://catalog.northeastern.edu/course-descriptions/",
        usedFor: "course catalog data",
      },
      {
        id:      "nubanner",
        label:   "nubanner.neu.edu",
        url:     "https://nubanner.neu.edu/StudentRegistrationSsb",
        usedFor: "term availability history",
      },
      {
        id:      "ratemyhusky",
        label:   "ratemyhusky.com",
        url:     "https://ratemyhusky.com",
        usedFor: "course & instructor rating links (TRACE / RateMyProfessor)",
      },
    ];
  },
};
