// ═══════════════════════════════════════════════════════════════════
// ADAPTER: northeastern/courseCatalog  (implements ICourseCatalog)
//
// DATA SOURCE HISTORY
// ───────────────────
// Course data originally came from the external/nu-courses git submodule
// (a fork of ninest/nu-courses), which re-served data from SearchNEU via
// husker.vercel.app. This let us bootstrap quickly with a ready-made API.
// The downside: dependency on an external hosted service we didn't control,
// with no ability to backfill history or shape the schema.
//
// We later built our own scrapers (scripts/scrape-catalog.js,
// scripts/scrape-availability.js) that pull directly from
// catalog.northeastern.edu and nubanner.neu.edu, writing to:
//   public/northeastern/catalog-courses.json  — course metadata
//   public/northeastern/term-history.json     — Banner enrollment history
//
// These files are now the source of truth. The external submodule is no
// longer in the fetch path.
//
// Primary catalog:  public/northeastern/catalog-courses.json (course metadata)
// Term history:     public/northeastern/term-history.json (Banner availability)
//   — generated by scripts/scrape-availability.js
//   — keyed by courseId → { termCode: boolean }
//
// Raw term codes: NEU Banner — YYYY = AY end year; 10=Fall, 30=Spring,
//                 40=Summer 1, 60=Summer 2  (decoded during normalization)
// ═══════════════════════════════════════════════════════════════════
import { subjectColor } from "../../core/courseModel.js";
import calendar from "./calendar.js";

const LOCAL_URL    = `${import.meta.env.BASE_URL}northeastern/catalog-courses.json`;
const HISTORY_URL  = `${import.meta.env.BASE_URL}northeastern/term-history.json`;
const COLLEGES_URL = `${import.meta.env.BASE_URL}northeastern/subject-colleges.json`;
// Supplemental nuPath source — catalog scraper sometimes drops nuPath on full re-scrapes.
// all-courses.json (SearchNEU) is used only to back-fill nuPath when catalog-courses has none.
const ALL_COURSES_URL = `${import.meta.env.BASE_URL}northeastern/all-courses.json`;

// ── Helpers ──────────────────────────────────────────────────────

/**
 * Compute which semester type IDs a course is offered in from termHistory.
 * When history has both true and false entries (from scrape-availability), a
 * semType is included only if it was offered in ≥ 50% of queried terms of that type.
 * When history has only positive evidence (from sections in all-courses.json), all
 * decoded semTypes are included — we don't penalise absence of evidence.
 */
function deriveTerms(termHistory) {
  const entries = Object.entries(termHistory);
  if (entries.length === 0) return [];

  const hasNegative = entries.some(([, v]) => v === false);
  if (!hasNegative) {
    // Only positive evidence: return all semTypes seen
    return [...new Set(entries.map(([code]) => calendar.decodeTermCode(code)).filter(Boolean))];
  }

  // Full history with negatives: P ≥ 0.5 threshold
  const semTypeIds = [...new Set(entries.map(([code]) => calendar.decodeTermCode(code)).filter(Boolean))];
  return semTypeIds.filter(id => {
    const ofType = entries.filter(([code]) => calendar.decodeTermCode(code) === id);
    return ofType.filter(([, v]) => v).length / ofType.length >= 0.5;
  });
}

// ── Normalization ────────────────────────────────────────────────

/** Enrollment-restriction patterns sometimes stored in the description field instead of actual content. */
const RESTRICTION_ONLY = /^(not open to|open only to|restricted to|required only for|graduate students only|undergraduate students only|for [a-z, ]+(students|majors|minors))/i;

function sanitizeDesc(raw) {
  const s = (raw || "").trim();
  if (!s) return "";
  if (s.length <= 150 && RESTRICTION_ONLY.test(s)) return "";
  return s;
}

/**
 * Normalize a raw catalog record into the internal Course shape.
 * Returns null if the record is missing a subject or number.
 *
 * @param {object} raw
 * @returns {import('../../ports/ICourseCatalog.js').Course|null}
 */
function normalizeCourse(raw, subjectColleges = {}, nuPathSupp = {}) {
  const subject = (raw.subject || raw.subjectCode || "").toUpperCase().trim();
  const number  = (raw.number  || raw.courseNumber || raw.num || "").trim();
  if (!subject || !number) return null;

  const id    = `${subject}${number}`;
  const title = raw.title || raw.name || "";
  const sh    = typeof raw.credits     === "number" ? raw.credits
               : typeof raw.credit     === "number" ? raw.credit
               : typeof raw.creditHours=== "number" ? raw.creditHours
               : 4;

  // sections[]{term} — de-duplicate term codes
  const rawTermCodes = raw.terms?.length
    ? raw.terms
    : (raw.sections || []).map(s => (typeof s === "string" ? s : s?.term ?? "")).filter(Boolean);
  const uniqueCodes = [...new Set(rawTermCodes)];

  // Build termHistory: each code we have section data for is confirmed offered (true).
  // false entries are added later when term-history.json is merged in fetchAll().
  const termHistory = {};
  for (const code of uniqueCodes) {
    if (calendar.decodeTermCode(code)) termHistory[code] = true;
  }

  // Derive terms from termHistory (P ≥ 0.5 per semType), or fall back to the raw
  // set of decoded codes if we only have positive evidence from sections.
  const uniqueTerms = deriveTerms(termHistory);

  const shMax = typeof raw.creditsMax === "number" && raw.creditsMax !== sh
    ? raw.creditsMax : null;
  const shMin = shMax !== null ? (sh ?? 4) : null;

  return {
    id, subject, number,
    code:         `${subject} ${number}`,
    title:        title.trim(),
    desc:         sanitizeDesc(raw.description),
    sh:           sh ?? 4,
    shMin,
    shMax,
    scheduleType: raw.scheduleType || "",
    prereqs:      raw.prereqs ?? raw.prerequisites ?? [],
    coreqs:       raw.coreqs  ?? raw.corequisites  ?? [],
    termHistory,
    terms:        uniqueTerms,
    attributes:   (raw.nuPath?.length ? raw.nuPath : nuPathSupp[id]) ?? raw.attributes ?? [],
    color:        subjectColor(subject),
    isCps:        (subjectColleges[subject] ?? "") === "PS",
  };
}

// ── Fetch ────────────────────────────────────────────────────────

async function tryFetch(url) {
  const res = await fetch(url, { cache: "no-cache" });
  if (!res.ok) throw new Error(`HTTP ${res.status} from ${url}`);
  const text = await res.text();
  if (text.trim().startsWith("<")) throw new Error(`Got HTML (not JSON) from ${url}`);
  return JSON.parse(text);
}

// ── Adapter ──────────────────────────────────────────────────────

/** @type {import('../../ports/ICourseCatalog.js').ICourseCatalog} */
export default {
  /**
   * Fetch the full course catalog and return all courses normalized to the Course shape.
   * Tries the bundled local JSON first; falls back to the live API.
   * Then merges term-history.json (if present) to enrich termHistory and recompute terms.
   */
  async fetchAll() {
    let json;
    try {
      json = await tryFetch(LOCAL_URL);
    } catch (err) {
      throw new Error(`Could not load course catalog from ${LOCAL_URL}: ${err.message}`);
    }
    const raw = Array.isArray(json) ? json : Object.values(json).flat();

    // Back-fill nuPath from all-courses.json when catalog-courses.json has it empty.
    // Keyed by courseId ("CS3500") for O(1) lookup.
    const nuPathSupp = {};
    try {
      const allCourses = await tryFetch(ALL_COURSES_URL);
      for (const c of (Array.isArray(allCourses) ? allCourses : [])) {
        const id = `${(c.subject || "").toUpperCase().trim()}${(c.number || "").trim()}`;
        if (id && c.nuPath?.length) nuPathSupp[id] = c.nuPath;
      }
    } catch { /* all-courses.json absent or malformed — proceed without supplement */ }

    let subjectColleges = {};
    try { subjectColleges = await tryFetch(COLLEGES_URL); } catch { /* file not yet generated */ }
    const courses = raw.map(r => normalizeCourse(r, subjectColleges, nuPathSupp)).filter(Boolean);

    // Merge Banner availability history if the file exists.
    // Silently skip if absent \u2014 app works without it.
    try {
      const history = await tryFetch(HISTORY_URL);
      if (history && typeof history === "object") {
        return courses.map(course => {
          const hist = history[course.id];
          if (!hist || typeof hist !== "object") return course;
          // Only merge past terms — future terms with false values skew probability.
          const pastHist = Object.fromEntries(
            Object.entries(hist).filter(([code]) => calendar.isTermPast(code))
          );
          const termHistory = { ...course.termHistory, ...pastHist };
          return { ...course, termHistory, terms: deriveTerms(termHistory) };
        });
      }
    } catch {
      // term-history.json not yet generated \u2014 proceed with sections-only data
    }
    return courses;
  },

  /** Normalize a single raw catalog record into the Course shape. */
  normalize: normalizeCourse,

  /**
   * Return the URL for the official Northeastern course catalog page for a course.
   * Links to the subject section; the registrar does not offer per-course-number deep links.
   */
  courseUrl(course) {
    return `https://catalog.northeastern.edu/course-descriptions/${course.subject.toLowerCase()}/`;
  },

  getSources() {
    return [
      {
        id:      "catalog",
        label:   "catalog.northeastern.edu",
        url:     "https://catalog.northeastern.edu/course-descriptions/",
        usedFor: "course catalog data",
      },
      {
        id:      "nubanner",
        label:   "nubanner.neu.edu",
        url:     "https://nubanner.neu.edu/StudentRegistrationSsb",
        usedFor: "term availability history",
      },
    ];
  },
};
