// ═══════════════════════════════════════════════════════════════════
// GENERATED by scripts/derive-term-windows.js — do not edit by hand.
//
// When each NU term begins and ends, measured from Banner section meeting
// dates over a rolling 5-year window (AY 2023–2028).
// Regenerated by the monthly update-courses workflow, so the thresholds
// follow the registrar's calendar instead of freezing a past one.
//
// Thresholds sit at median + 2·MADN of the sampled dates — the robust
// reading of "mean + 2σ", so one anomalous year (COVID pushed Spring 2022
// twelve days late) widens nothing.  `startSd`/`endSd` are the classical
// σ, reported for comparison only; nothing is derived from them.
//
// Where an exact arithmetic rule fits the whole sample it wins outright and
// carries no margin, because it is not an estimate: `startRule` names it and
// `lengthDays` gives the window length measured from it.
//
// Generated 2026-09-16.
// ═══════════════════════════════════════════════════════════════════

export default {
  "generatedAt": "2026-09-16",
  "yearsBack": 5,
  "sampledAY": [
    2023,
    2028
  ],
  "types": {
    "fall": {
      "n": 4,
      "years": [
        2022,
        2025
      ],
      "startScale": 2.22,
      "endScale": 0,
      "startSd": 1.83,
      "endSd": 1.5,
      "startRule": "laborDayPlus2",
      "lengthDays": 101,
      "startBuffer": 0,
      "lengthScale": 0.74
    },
    "spring": {
      "n": 4,
      "years": [
        2023,
        2026
      ],
      "startScale": 1.48,
      "endScale": 1.48,
      "startSd": 1.29,
      "endSd": 1.29,
      "start": {
        "month": 1,
        "day": 12
      },
      "end": {
        "month": 4,
        "day": 28
      },
      "startBuffer": 4
    },
    "sumA": {
      "n": 4,
      "years": [
        2023,
        2026
      ],
      "startScale": 0.74,
      "endScale": 2.22,
      "startSd": 1.26,
      "endSd": 2.5,
      "start": {
        "month": 5,
        "day": 9
      },
      "end": {
        "month": 6,
        "day": 28
      },
      "startBuffer": 3,
      "endClampedBy": "sumB"
    },
    "sumB": {
      "n": 4,
      "years": [
        2023,
        2026
      ],
      "startScale": 1.48,
      "endScale": 2.22,
      "startSd": 1.71,
      "endSd": 2.5,
      "start": {
        "month": 7,
        "day": 5
      },
      "end": {
        "month": 8,
        "day": 25
      },
      "startBuffer": 4
    }
  },
  "pinned": {
    "fall2026": {
      "start": "2026-09-09",
      "end": "2026-12-20"
    }
  }
};
